export const RESET_NUMBER_OF_DISCS = 'RESET_NUMBER_OF_DISCS';
export const PRODUCE_MOVES = 'PRODUCE_MOVES';
export const REPLACE_HEAD_MOVE = 'REPLACE_HEAD_MOVE';
export const CONSUME_DISC_MOVE = 'CONSUME_DISC_MOVE';
